#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /
    controller: App\Controller\HomeController::index
    
twig:
    path: /twig
    controller: App\Controller\HomeController::twig
    methods: [GET]
about:
    path: /about/{days}/{months}/{day_name}
    controller: App\Controller\HomeController::about
    defaults: {days: 7, months: 1, day_name : 'monday'}
    methods: [GET]
    requirements:
        days: '[0-9]+'
        months: '[0-9]+'
        day_name: '[a-zA-Z]+'
        
redir:
    path: /redir
    controller: App\Controller\HomeController::redir   
    
animal_index:
    path: /animal
    controller: App\Controller\AnimalController::index  
    
animal_save:
    path: /animal/save
    methods: [GET,POST]
    controller: App\Controller\AnimalController::save   
    
animal_get:
    path: /animal/get/{id}
    methods: [GET]
    controller: App\Controller\AnimalController::get_by_id 
    requirements:
        id: '[0-9]+'
